
let yeet = (itemName) => {
  ServerEvents.recipes(event => {
    event.remove({ output: itemName })
    event.remove({ input: itemName })
  })

  ServerEvents.tags('item', event => {
    event.add('c:hidden_from_recipe_viewers', itemName)
  })
}

let yeet_f = (itemName) => {
  ServerEvents.recipes(event => {
    event.remove({ output: Fluid.of(itemName) })
  })
  ServerEvents.tags('fluid', event => {
    event.add('c:hidden_from_recipe_viewers', itemName)
  })
}
yeet_f('creatoriocore:fuel_warm')

yeet('malum:crude_scythe')
yeet('malum:soul_stained_steel_scythe')
yeet('creatoriocore:fuel_warm_bucket')
yeet('creatoriocore:fuel_hot_bucket')
yeet('creatoriocore:fuel_blazing_bucket')
yeet('creatoriocore:fuel_searing_bucket')
yeet('creatoriocore:fuel_white_hot_bucket')
yeet('creatoriocore:fuel_infernal_bucket')
yeet('create_rns:resonance_buffer')
yeet('create_rns:shattering_resonator')
yeet('create_rns:stabilizing_resonator')
yeet('create_rns:resonator')
yeet('sophisticatedbackpacks:stack_upgrade_starter_tier')
yeet('sophisticatedbackpacks:stack_upgrade_tier_1')
yeet('sophisticatedbackpacks:stack_upgrade_tier_2')
yeet('sophisticatedbackpacks:stack_upgrade_tier_3')
yeet('sophisticatedbackpacks:stack_upgrade_tier_4')
yeet('sophisticatedbackpacks:stack_downgrade_tier_1')
yeet('sophisticatedbackpacks:stack_downgrade_tier_2')
yeet('sophisticatedbackpacks:stack_downgrade_tier_3')
yeet('sophisticatedbackpacks:stack_upgrade_omega_tier')
yeet('tfmg:coal_generator')
yeet('tfmg:diesel_generator')
yeet('tfmg:gas_generator')
yeet('tfmg:solar_panel')
yeet('tfmg:wind_turbine')
yeet('tfmg:creative_battery')
yeet('tfmg:cable')
yeet('tfmg:long_range_cable')
yeet('tfmg:cable_connector')
yeet('tfmg:voltage_transformer')
yeet('tfmg:current_limiter')
yeet('tfmg:junction_box')
yeet('tfmg:ground_cable')
yeet('tfmg:fuse_box')
yeet('tfmg:electric_switch')
yeet('tfmg:electric_motor')
yeet('tfmg:alternator')
yeet('tfmg:battery')
yeet('tfmg:electric_furnace')
yeet('tfmg:electric_smoker')
yeet('tfmg:electric_blast_furnace')
yeet('tfmg:powered_rail_adapter')
yeet('tfmg:red_light')
yeet('tfmg:yellow_light')
yeet('tfmg:green_light')
yeet('tfmg:electric_lamp')
yeet('tfmg:ceiling_light')
yeet('tfmg:redstone_relay')
yeet('tfmg:electric_redstone_relay')
yeet('tfmg:capacitor')
yeet('tfmg:resistor')
yeet('tfmg:voltmeter')
yeet('tfmg:ammeter')
yeet('tfmg:wattmeter')
yeet('tfmg:lightning_rod_electrode')
yeet('tfmg:copper_wire')
yeet('tfmg:insulated_copper_wire')
yeet('tfmg:copper_coil')
yeet('tfmg:magnet')
yeet('tfmg:electromagnet')
yeet('tfmg:electric_motor_component')
yeet('tfmg:carbon_brush')
yeet('tfmg:carbon_rod')
yeet('tfmg:fuse')
yeet('createdeco:zinc_sheet')
yeet('malum:iron_impetus')
yeet('malum:fractured_iron_impetus')
yeet('malum:copper_impetus')
yeet('malum:fractured_copper_impetus')
yeet('malum:gold_impetus')
yeet('malum:fractured_gold_impetus')
yeet('malum:aluminum_impetus')
yeet('malum:fractured_aluminum_impetus')
yeet('malum:nickel_impetus')
yeet('malum:fractured_nickel_impetus')
yeet('malum:silver_impetus')
yeet('malum:fractured_silver_impetus')
yeet('malum:tin_impetus')
yeet('malum:fractured_tin_impetus')
yeet('malum:zinc_impetus')
yeet('malum:fractured_zinc_impetus')
yeet('malum:osmium_impetus')
yeet('malum:fractured_osmium_impetus')
yeet('malum:lead_impetus')
yeet('malum:fractured_lead_impetus')
yeet('malum:uranium_impetus')
yeet('malum:fractured_uranium_impetus')
yeet('malum:cobalt_impetus')
yeet('malum:fractured_cobalt_impetus')
yeet('malum:zephyr_impetus')
yeet('malum:fractured_zephyr_impetus')
yeet('malum:alchemical_impetus')
yeet('malum:fractured_alchemical_impetus')
yeet('createadditionallogistics:andesite_encased_white_flexible_shaft')
yeet('createadditionallogistics:andesite_encased_orange_flexible_shaft')
yeet('createadditionallogistics:andesite_encased_magenta_flexible_shaft')
yeet('createadditionallogistics:andesite_encased_light_blue_flexible_shaft')
yeet('createadditionallogistics:andesite_encased_yellow_flexible_shaft')
yeet('createadditionallogistics:andesite_encased_lime_flexible_shaft')
yeet('createadditionallogistics:andesite_encased_pink_flexible_shaft')
yeet('createadditionallogistics:andesite_encased_gray_flexible_shaft')
yeet('createadditionallogistics:andesite_encased_light_gray_flexible_shaft')
yeet('createadditionallogistics:andesite_encased_cyan_flexible_shaft')
yeet('createadditionallogistics:andesite_encased_purple_flexible_shaft')
yeet('createadditionallogistics:andesite_encased_blue_flexible_shaft')
yeet('createadditionallogistics:andesite_encased_brown_flexible_shaft')
yeet('createadditionallogistics:andesite_encased_green_flexible_shaft')
yeet('createadditionallogistics:andesite_encased_red_flexible_shaft')
yeet('createadditionallogistics:andesite_encased_black_flexible_shaft')
yeet('createadditionallogistics:brass_encased_flexible_shaft')
yeet('createadditionallogistics:brass_encased_white_flexible_shaft')
yeet('createadditionallogistics:brass_encased_orange_flexible_shaft')
yeet('createadditionallogistics:brass_encased_magenta_flexible_shaft')
yeet('createadditionallogistics:brass_encased_light_blue_flexible_shaft')
yeet('createadditionallogistics:brass_encased_yellow_flexible_shaft')
yeet('createadditionallogistics:brass_encased_lime_flexible_shaft')
yeet('createadditionallogistics:brass_encased_pink_flexible_shaft')
yeet('createadditionallogistics:brass_encased_gray_flexible_shaft')
yeet('createadditionallogistics:brass_encased_light_gray_flexible_shaft')
yeet('createadditionallogistics:brass_encased_cyan_flexible_shaft')
yeet('createadditionallogistics:brass_encased_purple_flexible_shaft')
yeet('createadditionallogistics:brass_encased_blue_flexible_shaft')
yeet('createadditionallogistics:brass_encased_brown_flexible_shaft')
yeet('createadditionallogistics:brass_encased_green_flexible_shaft')
yeet('createadditionallogistics:brass_encased_red_flexible_shaft')
yeet('createadditionallogistics:brass_encased_black_flexible_shaft')
yeet('createadditionallogistics:copper_encased_flexible_shaft')
yeet('createadditionallogistics:copper_encased_white_flexible_shaft')
yeet('createadditionallogistics:copper_encased_orange_flexible_shaft')
yeet('createadditionallogistics:copper_encased_magenta_flexible_shaft')
yeet('createadditionallogistics:copper_encased_light_blue_flexible_shaft')
yeet('createadditionallogistics:copper_encased_yellow_flexible_shaft')
yeet('createadditionallogistics:copper_encased_lime_flexible_shaft')
yeet('createadditionallogistics:copper_encased_pink_flexible_shaft')
yeet('createadditionallogistics:copper_encased_gray_flexible_shaft')
yeet('createadditionallogistics:copper_encased_light_gray_flexible_shaft')
yeet('createadditionallogistics:copper_encased_cyan_flexible_shaft')
yeet('createadditionallogistics:copper_encased_purple_flexible_shaft')
yeet('createadditionallogistics:copper_encased_blue_flexible_shaft')
yeet('createadditionallogistics:copper_encased_brown_flexible_shaft')
yeet('createadditionallogistics:copper_encased_green_flexible_shaft')
yeet('createadditionallogistics:industrial_iron_encased_light_gray_flexible_shaft')
yeet('createadditionallogistics:industrial_iron_encased_gray_flexible_shaft')
yeet('createadditionallogistics:industrial_iron_encased_pink_flexible_shaft')
yeet('createadditionallogistics:industrial_iron_encased_lime_flexible_shaft')
yeet('createadditionallogistics:industrial_iron_encased_yellow_flexible_shaft')
yeet('createadditionallogistics:industrial_iron_encased_light_blue_flexible_shaft')
yeet('createadditionallogistics:industrial_iron_encased_magenta_flexible_shaft')
yeet('createadditionallogistics:industrial_iron_encased_orange_flexible_shaft')
yeet('createadditionallogistics:industrial_iron_encased_white_flexible_shaft')
yeet('createadditionallogistics:industrial_iron_encased_flexible_shaft')
yeet('createadditionallogistics:copper_encased_black_flexible_shaft')
yeet('createadditionallogistics:copper_encased_red_flexible_shaft')
yeet('createadditionallogistics:industrial_iron_encased_cyan_flexible_shaft')
yeet('createadditionallogistics:industrial_iron_encased_purple_flexible_shaft')
yeet('createadditionallogistics:industrial_iron_encased_blue_flexible_shaft')
yeet('createadditionallogistics:industrial_iron_encased_brown_flexible_shaft')
yeet('createadditionallogistics:industrial_iron_encased_green_flexible_shaft')
yeet('createadditionallogistics:industrial_iron_encased_red_flexible_shaft')
yeet('createadditionallogistics:industrial_iron_encased_black_flexible_shaft')
yeet('createadditionallogistics:weathered_iron_encased_flexible_shaft')
yeet('createadditionallogistics:weathered_iron_encased_white_flexible_shaft')
yeet('createadditionallogistics:weathered_iron_encased_orange_flexible_shaft')
yeet('createadditionallogistics:weathered_iron_encased_magenta_flexible_shaft')
yeet('createadditionallogistics:weathered_iron_encased_light_blue_flexible_shaft')
yeet('createadditionallogistics:andesite_encased_flexible_shaft')
yeet('createadditionallogistics:weathered_iron_encased_black_flexible_shaft')
yeet('createadditionallogistics:weathered_iron_encased_red_flexible_shaft')
yeet('createadditionallogistics:weathered_iron_encased_green_flexible_shaft')
yeet('createadditionallogistics:weathered_iron_encased_brown_flexible_shaft')
yeet('createadditionallogistics:weathered_iron_encased_blue_flexible_shaft')
yeet('createadditionallogistics:weathered_iron_encased_purple_flexible_shaft')
yeet('createadditionallogistics:weathered_iron_encased_cyan_flexible_shaft')
yeet('createadditionallogistics:weathered_iron_encased_light_gray_flexible_shaft')
yeet('createadditionallogistics:weathered_iron_encased_gray_flexible_shaft')
yeet('createadditionallogistics:weathered_iron_encased_pink_flexible_shaft')
yeet('createadditionallogistics:weathered_iron_encased_lime_flexible_shaft')
yeet('createadditionallogistics:weathered_iron_encased_yellow_flexible_shaft')
yeet('createadditionallogistics:weathered_iron_encased_lazy_shaft')
yeet('createadditionallogistics:andesite_encased_lazy_cogwheel')
yeet('createadditionallogistics:andesite_encased_lazy_large_cogwheel')
yeet('createadditionallogistics:brass_encased_lazy_cogwheel')
yeet('createadditionallogistics:brass_encased_lazy_large_cogwheel')
yeet('createadditionallogistics:copper_encased_lazy_cogwheel')
yeet('createadditionallogistics:copper_encased_lazy_large_cogwheel')
yeet('createadditionallogistics:industrial_iron_encased_lazy_cogwheel')
yeet('createadditionallogistics:industrial_iron_encased_lazy_large_cogwheel')
yeet('createadditionallogistics:weathered_iron_encased_lazy_cogwheel')
yeet('createadditionallogistics:weathered_iron_encased_lazy_large_cogwheel')
yeet('createadditionallogistics:industrial_iron_encased_lazy_shaft')
yeet('createadditionallogistics:copper_encased_lazy_shaft')
yeet('createadditionallogistics:brass_encased_lazy_shaft')
yeet('createadditionallogistics:andesite_encased_lazy_shaft')
yeet('createadditionallogistics:lazy_shaft')
yeet('createadditionallogistics:lazy_cogwheel')
yeet('createadditionallogistics:lazy_large_cogwheel')
yeet('createadditionallogistics:flexible_shaft')
yeet('createadditionallogistics:white_flexible_shaft')
yeet('createadditionallogistics:orange_flexible_shaft')
yeet('createadditionallogistics:magenta_flexible_shaft')
yeet('createadditionallogistics:light_blue_flexible_shaft')
yeet('createadditionallogistics:yellow_flexible_shaft')
yeet('createadditionallogistics:lime_flexible_shaft')
yeet('createadditionallogistics:pink_flexible_shaft')
yeet('createadditionallogistics:gray_flexible_shaft')
yeet('createadditionallogistics:light_gray_flexible_shaft')
yeet('createadditionallogistics:cyan_flexible_shaft')
yeet('createadditionallogistics:purple_flexible_shaft')
yeet('createadditionallogistics:blue_flexible_shaft')
yeet('createadditionallogistics:brown_flexible_shaft')
yeet('createadditionallogistics:green_flexible_shaft')
yeet('createadditionallogistics:red_flexible_shaft')
yeet('createadditionallogistics:black_flexible_shaft')
yeet('minecraft:crafter')
yeet('fluidlogistics:smart_faucet')
yeet('petrolsparts:corner_shaft')
yeet('createcasing:industrial_iron_gearbox')
yeet('createcasing:vertical_industrial_iron_gearbox')
yeet('createcasing:industrial_iron_press')
yeet('createcasing:industrial_iron_mixer')
yeet('createcasing:industrial_iron_depot')
yeet('createcasing:industrial_iron_encased_chain_drive')
yeet('createcasing:industrial_iron_adjustable_chain_gearshift')
yeet('createcasing:industrial_iron_configurable_gearbox')
yeet('createcasing:industrial_iron_chain_conveyor')
yeet('createcasing:industrial_iron_gearshift')
yeet('createcasing:industrial_iron_clutch')
yeet('createcasing:industrial_iron_deployer')
yeet('createcasing:industrial_iron_portable_storage_interface')
yeet('createcasing:industrial_iron_encased_fan')
yeet('createcasing:industrial_iron_mechanical_harvester')
yeet('createcasing:industrial_iron_mechanical_saw')
yeet('createcasing:industrial_iron_mechanical_drill')
yeet('createcasing:industrial_iron_mechanical_plough')
yeet('createcasing:industrial_iron_mechanical_roller')
yeet('createcasing:copper_gearbox')
yeet('createcasing:vertical_copper_gearbox')
yeet('createcasing:copper_press')
yeet('createcasing:copper_mixer')
yeet('createcasing:copper_depot')
yeet('createcasing:copper_encased_chain_drive')
yeet('createcasing:copper_adjustable_chain_gearshift')
yeet('createcasing:copper_configurable_gearbox')
yeet('createcasing:copper_chain_conveyor')
yeet('createcasing:copper_gearshift')
yeet('createcasing:copper_clutch')
yeet('createcasing:copper_deployer')
yeet('createcasing:copper_portable_storage_interface')
yeet('createcasing:copper_encased_fan')
yeet('createcasing:copper_mechanical_harvester')
yeet('createcasing:copper_mechanical_saw')
yeet('createcasing:copper_mechanical_drill')
yeet('createcasing:copper_encased_fan')
yeet('createcasing:copper_mechanical_harvester')
yeet('createcasing:copper_portable_storage_interface')
yeet('createcasing:weathered_iron_gearbox')
yeet('createcasing:vertical_weathered_iron_gearbox')
yeet('createcasing:weathered_iron_press')
yeet('createcasing:weathered_iron_mixer')
yeet('createcasing:weathered_iron_depot')
yeet('createcasing:weathered_iron_encased_chain_drive')
yeet('createcasing:weathered_iron_adjustable_chain_gearshift')
yeet('createcasing:weathered_iron_configurable_gearbox')
yeet('createcasing:weathered_iron_chain_conveyor')
yeet('createcasing:weathered_iron_gearshift')
yeet('createcasing:weathered_iron_clutch')
yeet('createcasing:weathered_iron_deployer')
yeet('createcasing:weathered_iron_portable_storage_interface')
yeet('createcasing:weathered_iron_encased_fan')
yeet('createcasing:weathered_iron_mechanical_harvester')
yeet('createcasing:weathered_iron_mechanical_saw')
yeet('createcasing:weathered_iron_mechanical_drill')
yeet('createcasing:weathered_iron_mechanical_plough')
yeet('createcasing:weathered_iron_mechanical_roller')
yeet('create_new_age:basic_motor')
yeet('create_new_age:advanced_motor')
yeet('create_new_age:reinforced_motor')
yeet('create_new_age:basic_motor_extension')
yeet('create_new_age:advanced_motor_extension')
yeet('create_new_age:electrical_connector')
yeet('create_new_age:copper_wire')
yeet('create_new_age:overcharged_iron_wire')
yeet('create_new_age:overcharged_golden_wire')
yeet('create_new_age:overcharged_diamond_wire')
yeet('create_new_age:incomplete_wire')
yeet('create_new_age:copper_wire_block')
yeet('create_new_age:overcharged_iron_wire_block')
yeet('create_new_age:overcharged_golden_wire_block')
yeet('create_new_age:overcharged_diamond_wire_block')
yeet('create_new_age:magnetite_block')
yeet('create_new_age:redstone_magnet')
yeet('create_new_age:layered_magnet')
yeet('create_new_age:fluxuated_magnetite')
yeet('create_new_age:netherite_magnet')
yeet('create_new_age:reactor_casing')
yeet('create_new_age:reactor_rod')
yeet('create_new_age:reactor_glass')
yeet('create_new_age:reactor_fuel_acceptor')
yeet('create_new_age:reactor_heat_vent')

ServerEvents.recipes(event => {

  event.remove({ id: 'create:item_application/copper_casing_from_wood' })
  event.remove({ id: 'create:item_application/copper_casing_from_log' })
  event.remove({ id: 'farmersdelight:wheat_dough_from_water' })
  event.remove({ id: 'farmersdelight:wheat_dough_from_egg' })
  event.remove({ id: 'create_new_age:energising/experience_bottle' })
  event.remove({ id: 'create_new_age:shaped/generator_coil' })
  event.remove({ id: 'dndesires:crafting/gold_mixer' })
  event.remove({ id: 'dndesires:dragon_breathing/dragon_breath' })
  event.remove({ id: 'create:haunting/soul_soil' })
  event.remove({ id: 'create:item_application/andesite_casing_from_log_using_deployer' })
  event.remove({ id: 'create:item_application/andesite_casing_from_wood_using_deployer' })
  event.remove({ id: 'create:item_application/andesite_casing_from_log' })
  event.remove({ id: 'create:item_application/andesite_casing_from_wood' })
  event.remove({ id: 'rubberworks:crafting/compressor' })
  event.remove({ id: 'create:industrial_iron_block_from_ingots_iron_stonecutting' })
  event.remove({ id: 'create:mixing/andesite_alloy_from_zinc' })
  event.remove({ id: 'create:mixing/andesite_alloy' })
  event.remove({ id: 'create:crafting/materials/andesite_alloy' })
  event.remove({ id: 'create:crafting/materials/andesite_alloy_from_zinc' })

  event.remove({ id: 'create:crafting/materials/andesite_alloy_block' })
  event.remove({ id: 'create:crafting/materials/andesite_alloy_from_block' })
  event.remove({ id: 'rubberworks:compacting/rubber' })
  event.remove({ id: 'create_rns:miner_bearing' })

  event.remove({ id: 'create:crafting/kinetics/wrench' })
  event.remove({ id: 'create:crafting/materials/rose_quartz' })
  event.remove({ id: 'create:crafting/kinetics/deployer' })
  event.remove({ id: 'create:crafting/logistics/package_frogport' })
  event.remove({ id: 'dndesires:crafting/frogport' })
  event.remove({ id: 'create:crafting/logistics/stock_link' })
  event.remove({ id: 'create:crafting/logistics/content_observer' })
  event.remove({ id: 'create:crafting/materials/transmitter' })

  event.remove({ id: 'create:crushing/redstone_ore' })
  event.remove({ id: 'create:crushing/deepslate_redstone_ore' })
  event.remove({ id: 'create:item_application/brass_casing_from_wood' })
  event.remove({ id: 'create:item_application/brass_casing_from_log' })
  event.remove({ id: 'create:item_application/brass_casing_from_wood_using_deployer' })
  event.remove({ id: 'create:item_application/brass_casing_from_log_using_deployer' })
  event.remove({ id: 'create:mechanical_crafting/crushing_wheel' })
  event.remove({ id: 'create:item_application/railway_casing_using_deployer' })
  event.remove({ id: 'create:item_application/railway_casing' })
  event.remove({ id: 'tfmg:crafting/materials/fireproof_bricks' })
  event.remove({ id: 'create:sequenced_assembly/precision_mechanism' })
  event.remove({ id: 'create_connected:sequenced_assembly/control_chip' })
  event.remove({ id: 'createvintageneoforged:craft/spring_coiling_machine_wheel' })
  event.remove({ id: 'create:crafting/logistics/factory_gauge' })
  event.remove({ id: 'create:crafting/kinetics/steam_engine' })
  event.remove({ id: 'farmersdelight:canvas' })
  event.remove({ type: 'createvintageneoforged:centrifuge' })
  event.remove({ id: 'supplementaries:lapis_bricks' })
  event.remove({ id: 'createadditionallogistics:crafting/logistics/package_accelerator' })
  event.remove({ id: 'dndesires:crafting/omni_gearbox' })
  event.remove({ id: 'dndesires:crafting/lapis_lazuli_shard_from_lapis_lazuli' })
  event.remove({ id: 'dndesires:crafting/lapis_lazuli_shard_from_lapis_lazuli' })
  event.remove({ id: 'dndesires:seething/lapis_lazuli_shard_from_calcite' })
  event.remove({ id: 'tfmg:item_application/steel_casing' })
  event.remove({ id: 'tfmg:item_application/steel_casing_using_deployer' })
  event.remove({ id: 'create_rns:tin_deposit_block' })
  event.remove({ id: 'create_rns:uranium_deposit_block' })
  event.remove({ id: 'create_rns:silver_deposit_block' })
  event.remove({ id: 'create_rns:thorium_deposit_block' })
  event.remove({ id: 'create_rns:cobalt_deposit_block' })
  event.remove({ id: 'tfmg:sequenced_assembly/generator' })
  event.remove({ id: 'powergrid:item_application/conductive_casing' })
  event.remove({ id: 'malum:soul_stained_steel_plating' })
  event.remove({ id: 'malum:spirit_infusion/soul_stained_steel_ingot' })

  //TFMG
  event.remove({ id: 'tfmg:casting/steel' })
  event.remove({ id: 'tfmg:compacting/cast_iron' })
  event.remove({ id: 'tfmg:smelting/fireproof_brick' })
  event.remove({ id: 'tfmg:industrial_blasting/steel_from_dust' })
  event.remove({ id: 'tfmg:industrial_blasting/steel_from_raw_iron' })
  event.remove({ id: 'tfmg:industrial_blasting/silicon' })
  event.remove({ id: 'tfmg:industrial_blasting/steel' })
  event.remove({ id: 'tfmg:casting/silicon' })
  event.remove({ id: 'tfmg:crafting/materials/steel_distillation_controller' })
  event.remove({ id: 'tfmg:crafting/materials/pumpjack_crank' })
  event.remove({ id: 'tfmg:crafting/materials/industrial_mixer' })
  event.remove({ id: 'tfmg:sequenced_assembly/unfinished_circuit_board' })
  event.remove({ id: 'tfmg:crafting/materials/blast_furnace_output' })
  event.remove({ id: 'tfmg:crafting/materials/blast_furnace_hatch' })
})




ServerEvents.tags('block', event => {
  event.remove('aether:aether_portal_blocks', 'minecraft:glowstone')
})